version: "3"
services:
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - "5000:5000" # Map container port 5000 to host port 5000
    volumes:
      - /app/node_modules
      - ./server:/app
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    ports:
      - "3000:3000" # Map container port 3000 to host port 3000
    volumes:
      - /app/node_modules
      - ./client:/app
  nginx:
    depends_on:
      - server
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "80:80" # Map container port 80 to host port 80
